# Generated by Django 3.2.7 on 2021-10-04 10:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, help_text='The order ID by which the system refers', primary_key=True, serialize=False)),
                ('request_id_instamojo', models.UUIDField(default=uuid.uuid4, help_text='The Request ID by which the INSTAMOJO refers')),
                ('instamojo_order_id', models.CharField(blank=True, help_text='The order ID by which the INSTAMOJO refers', max_length=250, null=True)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success')], default='P', help_text='The status of payment', max_length=250)),
                ('orders_list', models.TextField(help_text='The orders list value')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ('-created_at',),
            },
        ),
    ]
