# Generated by Django 3.2.7 on 2021-09-24 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(help_text='The status of payment', max_length=250)),
                ('orders_json', models.TextField(help_text='The orders json value')),
            ],
        ),
    ]
