# Generated by Django 3.2.8 on 2021-11-01 11:33

from django.db import migrations, models

import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_sponser_image"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboOffers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combo_id",
                    models.CharField(
                        default=payments.models.generate_combo_code,
                        help_text="The Combo ID by which the system refers",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "if_squad",
                    models.BooleanField(default=True,
                                        help_text="If Squad Option is there"),
                ),
                ("squad", models.IntegerField(default=0)),
                (
                    "if_solo",
                    models.BooleanField(default=True,
                                        help_text="If Solo Option is there"),
                ),
                ("solo", models.IntegerField(default=0)),
                ("games", models.ManyToManyField(to="main.Games")),
            ],
            options={
                "verbose_name_plural": "Combo Offers",
            },
        ),
    ]
