# Generated by Django 3.2.7 on 2021-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='orders_json',
            new_name='orders_list',
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success')], default='P', help_text='The status of payment', max_length=250),
        ),
    ]
