# Generated by Django 3.2.7 on 2021-09-26 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210926_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order_id_instamojo',
            field=models.UUIDField(default=uuid.uuid4, help_text='The order ID by which the INSTAMOJO refers'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The order ID by which the system refers', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='orders_list',
            field=models.TextField(help_text='The orders list value'),
        ),
    ]
