# Generated by Django 3.2.9 on 2021-11-09 06:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_combooffers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="instamojo_order_id",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="request_id_instamojo",
        ),
        migrations.AddField(
            model_name="payments",
            name="order_id_merchant",
            field=models.CharField(
                blank=True,
                help_text="The Order ID by which the Razorpay refers",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_id_merchant",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                help_text="The Payment ID by which the Razorpay refers",
                max_length=250,
                null=True,
            ),
        ),
    ]
