# Generated by Django 3.2.7 on 2021-09-28 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
