# Generated by Django 3.2.7 on 2021-09-28 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payments_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='order_id_instamojo',
            new_name='instamojo_order_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='request_id_instamojo',
            field=models.UUIDField(default=uuid.uuid4, help_text='The Request ID by which the INSTAMOJO refers'),
        ),
    ]
