# Generated by Django 3.2.7 on 2021-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20210928_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='instamojo_order_id',
            field=models.CharField(blank=True, help_text='The order ID by which the INSTAMOJO refers', max_length=250, null=True),
        ),
    ]
