# Generated by Django 3.2.7 on 2021-09-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payments_instamojo_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Payments'},
        ),
    ]
