# Generated by Django 3.2.8 on 2021-10-18 13:43

from django.db import migrations, models
import referral.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('name', models.CharField(help_text='Name of the University / Person', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Optional', null=True)),
                ('referral_code', models.CharField(default=referral.models.generate_referral_code, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
