# Generated by Django 3.2.8 on 2021-10-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referral.referral'),
        ),
    ]
