# Generated by Django 3.2.7 on 2021-09-25 07:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='amount',
        ),
        migrations.AddField(
            model_name='gamegroup',
            name='group_unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, to='accounts.GameGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Registration No'),
        ),
    ]
