# Generated by Django 3.2.7 on 2021-09-25 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210925_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=250, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_no',
            field=models.CharField(help_text='Your college issued ID (Optional)', max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Registration No'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=250, verbose_name='state'),
        ),
    ]
