# Generated by Django 3.2.7 on 2021-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210925_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_name',
            field=models.CharField(default='LPU', max_length=250, verbose_name='University or College Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=250, null=True, verbose_name='country'),
        ),
    ]
