# Generated by Django 3.2.7 on 2021-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210925_2017'),
        ('accounts', '0005_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegroup',
            name='games',
        ),
        migrations.AddField(
            model_name='gamegroup',
            name='solo_games',
            field=models.ManyToManyField(related_name='solo_games', to='main.Games'),
        ),
        migrations.AddField(
            model_name='gamegroup',
            name='squad_games',
            field=models.ManyToManyField(related_name='squad_games', to='main.Games'),
        ),
    ]
