# Generated by Django 4.0.1 on 2022-01-10 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_address2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="It should be +91 67xxx",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="phone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_no",
            field=models.CharField(
                blank=True,
                help_text="Your college issued ID (Optional)",
                max_length=250,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Registration No",
            ),
        ),
    ]
