# Generated by Django 3.2.7 on 2021-09-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210925_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegroup',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='gamegroup',
            name='solo_games',
        ),
        migrations.RemoveField(
            model_name='gamegroup',
            name='squad_games',
        ),
        migrations.RemoveField(
            model_name='gamegroup',
            name='users',
        ),
    ]
