# Generated by Django 3.2.7 on 2021-09-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payments_options'),
        ('accounts', '0008_auto_20210926_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(help_text='This is to be filled by computer', to='payments.Payments'),
        ),
    ]
