# Generated by Django 3.2.7 on 2021-09-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamegroup'),
        ('payments', '0004_alter_payments_options'),
        ('accounts', '0009_auto_20210928_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='main.GameGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, help_text='This is to be filled by computer', to='payments.Payments'),
        ),
    ]
