# Generated by Django 3.2.7 on 2021-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gamegroup_group_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_auto_20210928_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_groups',
            field=models.ManyToManyField(blank=True, to='main.GameGroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
