# Generated by Django 3.2.7 on 2021-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211003_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_groups',
        ),
    ]
