# Generated by Django 3.2.7 on 2021-10-04 10:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the game",
                                     max_length=200),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="About this short event, better keep it in between 100 characters",
                        validators=[
                            django.core.validators.MinLengthValidator(13),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                    ),
                ),
                (
                    "long_description",
                    models.TextField(help_text="Here explain everything"),
                ),
                ("image_url",
                 models.URLField(help_text="Url of the game image")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("a", "ALL"),
                            ("m", "Mobile"),
                            ("p", "PC"),
                            ("ps", "Play Station"),
                        ],
                        default="A",
                        max_length=11,
                    ),
                ),
                ("has_solo_entry", models.BooleanField(default=True)),
                (
                    "solo_entry",
                    models.IntegerField(
                        help_text="Enter the Solo entry price"),
                ),
                ("has_squad_entry", models.BooleanField(default=True)),
                (
                    "squad_entry",
                    models.IntegerField(
                        help_text="Enter the Sqaud entry price"),
                ),
                ("squad_entry_members", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name_plural": "Games",
            },
        ),
        migrations.CreateModel(
            name="GameGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_unique_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "group_name",
                    models.CharField(blank=True,
                                     max_length=250,
                                     null=True,
                                     unique=True),
                ),
                (
                    "solo_or_squad",
                    models.CharField(
                        choices=[("sq", "SQUAD"), ("so", "SOLO")],
                        default="sq",
                        max_length=15,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.games"),
                ),
                (
                    "payment_id",
                    models.ForeignKey(
                        help_text="This is to be filled by computer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payments",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
