# Generated by Django 3.2.7 on 2021-09-24 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the game', max_length=200)),
                ('short_description', models.TextField(help_text='About this short event, better keep it in between 100 characters', validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(100)])),
                ('long_description', models.TextField(help_text='Here explain everything')),
                ('image_url', models.URLField(help_text='Url of the game image')),
                ('platform', models.CharField(choices=[('a', 'ALL'), ('m', 'Mobile'), ('p', 'PC'), ('pc', 'Play Station')], default='A', max_length=11)),
                ('solo_entry', models.IntegerField(help_text='Enter the Solo entry price')),
                ('squad_entry', models.IntegerField(help_text='Enter the Sqaud entry price')),
            ],
        ),
    ]
