# Generated by Django 3.2.7 on 2021-09-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='platform',
            field=models.CharField(choices=[('a', 'ALL'), ('m', 'Mobile'), ('p', 'PC'), ('ps', 'Play Station')], default='A', max_length=11),
        ),
    ]
