# Generated by Django 3.2.7 on 2021-09-26 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210926_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210925_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_unique_id', models.UUIDField(default=uuid.uuid4)),
                ('solo_or_squad', models.CharField(choices=[('sq', 'SQUAD'), ('so', 'SOLO')], default='sq', max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games')),
                ('payment_id', models.ForeignKey(help_text='This is to be filled by computer', on_delete=django.db.models.deletion.CASCADE, to='payments.payments')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
