# Generated by Django 3.2.8 on 2021-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sponser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="image_url",
            field=models.CharField(help_text="Url of the game image",
                                   max_length=250),
        ),
    ]
