# Generated by Django 3.2.7 on 2021-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='group_name',
            field=models.CharField(default='LPU', max_length=250),
            preserve_default=False,
        ),
    ]
