# Generated by Django 3.2.8 on 2021-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_games_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='image',
            field=models.TextField(max_length=250),
        ),
    ]
