# Generated by Django 3.2.7 on 2021-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gamegroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
