# Generated by Django 3.2.8 on 2021-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sponser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
