# Generated by Django 3.2.8 on 2021-11-01 15:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sponser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_unique_id',
            field=models.CharField(default=main.models.generate_unique_id, help_text='The Games ID by which the system refers', max_length=250),
        ),
    ]
