# Generated by Django 3.2.7 on 2021-09-29 12:18

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_gamegroup_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnnouncements',
            fields=[
                ('announcement_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('announncement_message', models.TextField(verbose_name='The announcement that you want to give globally')),
                ('announncement_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Global Announcements',
                'ordering': ('-announncement_creation_date',),
            },
        ),
        migrations.CreateModel(
            name='UsersAnnouncements',
            fields=[
                ('announcement_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('announncement_message', models.TextField(verbose_name='The announcement that you want to give per or user wise')),
                ('announncement_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Announcements',
                'ordering': ('-announncement_creation_date',),
            },
        ),
        migrations.CreateModel(
            name='GroupsAnnouncements',
            fields=[
                ('announcement_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('announncement_message', models.TextField(verbose_name='The announcement that you want to give Group Wise')),
                ('announncement_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(to='main.GameGroup')),
            ],
            options={
                'verbose_name_plural': 'Groups Announcements',
                'ordering': ('-announncement_creation_date',),
            },
        ),
    ]
