# Generated by Django 3.2.8 on 2021-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalannouncements",
            name="announcement_heading",
            field=models.CharField(default="New Announcement Here",
                                   max_length=250),
        ),
        migrations.AddField(
            model_name="groupsannouncements",
            name="announcement_heading",
            field=models.CharField(default="New Announcement Here",
                                   max_length=250),
        ),
        migrations.AddField(
            model_name="usersannouncements",
            name="announcement_heading",
            field=models.CharField(default="New Announcement Here",
                                   max_length=250),
        ),
    ]
