# Generated by Django 3.2.7 on 2021-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.DecimalField(decimal_places=10, help_text='Amount paid by the person/team', max_digits=19, null=True),
        ),
    ]
