# Generated by Django 3.2.7 on 2021-09-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('user', '0003_alter_user_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ForeignKey(help_text='This is to be filled by computer', null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payments'),
        ),
    ]
